{extends innerLayout.phtml}
{block group}
<h3>{$nazev}</h3>
       <div class="config-cont-box">
       
            {$control['doprava'][$druh]->control}
       
        </div>

            
{/block}
{block obsah}
 <div id="config-cont" class="niceform">
    
{control doprava begin}
{control doprava errors}
    	{include #group, 'nazev' => 'Doprava', druh => doprava}
    	{include #group, 'nazev' => 'Platba', druh => platby}
  		{control doprava validation}
    
    <input type="submit">
{control doprava end}
</div>
    
    {include #sidebar}

<div id="button-line">
<a onclick="submit();" href=""><span class="button-green-mini button-mini-right">Pokračovat</span></a>
{include #buttonZrusit}
</div> 


